# This is a basic workflow to help you get started with Actions

name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          #sudo log show --predicate "logType == error"  | grep osascript
          sw_vers
          brew install unxip
          brew install xcodesorg/made/xcodes
          xcodes list

